/// <summary>
/// Enum of contextual keys for tracker events
/// </summary>
public enum TrackerContextKeys
{
	BoatLayout,
	CrewMemberName,
	CrewMemberPosition,
	CrewMemberSessionsInTeam,
	CupFinishingPosition,
	CurrentSession,
	CurrentTalkTime,
	DialogueID,
	DialogueStyle,
	EventID,
	FinishingPosition,
	FiringCost,
	GameName,
	HiringCost,
	HoverKey,
	IdealCorrectMemberWrongPosition,
	IdealCorrectPlacement,
	IdealIncorrectPlacement,
	LearningPillID,
	PositionCrewMember,
	PositionName,
	PreviousCrewMemberInPosition,
	PreviousCrewMemberPosition,
	QuestionAsked,
	QuestionCost,
	RaceNumber,
	RaceStartTalkTime,
	RemainingSessions,
	Score,
	ScoreAverage,
	SessionType,
	SessionsIncludedCount,
	SessionsSinceBoatLayoutChange,
	SizeOfTeam,
	TriggerUI
}