//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayGen.RAGE.SportsTeamManager.Simulation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayGen.RAGE.SportsTeamManager.Simulation.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;RandomHairColor&quot;: true,
        ///	&quot;HairTypesCount&quot;: 5,
        ///	&quot;OutfitTypesCount&quot;: 3,
        ///	&quot;LightSkinColorValues&quot;: [
        ///		255,
        ///		255,
        ///		255
        ///	],
        ///	&quot;MediumSkinColorValues&quot;: [
        ///		195,
        ///		186,
        ///		135
        ///	],
        ///	&quot;DarkSkinColorValues&quot;: [
        ///		127,
        ///		109,
        ///		77
        ///	],
        ///	&quot;BlondeHairColorValues&quot;: [
        ///		231,
        ///		231,
        ///		115
        ///	],
        ///	&quot;BrownHairColorValues&quot;: [
        ///		86,
        ///		57,
        ///		13
        ///	],
        ///	&quot;BlackHairColorValues&quot;: [
        ///		39,
        ///		24,
        ///		2
        ///	],
        ///	&quot;GingerHairColorValues&quot;: [
        ///		204,
        ///		108,
        ///		6
        ///	],
        ///	&quot;BlueEyeColorValues&quot;: [
        ///		30,
        ///		51,
        ///		90
        ///	],        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string avatar_config {
            get {
                return ResourceManager.GetString("avatar_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Dinghy&quot;: [
        ///		&quot;Skipper&quot;,
        ///		&quot;Navigator&quot;,
        ///		&quot;MidBowman&quot;
        ///	],
        ///	&quot;AltDinghy&quot;: [
        ///		&quot;Skipper&quot;,
        ///		&quot;Helmsman&quot;,
        ///		&quot;MidBowman&quot;
        ///	],
        ///	&quot;BiggerDinghy&quot;: [
        ///		&quot;Skipper&quot;,
        ///		&quot;Navigator&quot;,
        ///		&quot;Helmsman&quot;,
        ///		&quot;Pitman&quot;
        ///	],
        ///	&quot;BiggestDinghy&quot;: [
        ///		&quot;Skipper&quot;,
        ///		&quot;Navigator&quot;,
        ///		&quot;Helmsman&quot;,
        ///		&quot;Trimmer&quot;,
        ///		&quot;Pitman&quot;,
        ///		&quot;MidBowman&quot;
        ///	]
        ///}
        ///.
        /// </summary>
        public static string boat_config {
            get {
                return ResourceManager.GetString("boat_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;GoodPositionRating&quot;: 7,
        ///	&quot;BadPositionRating&quot;: 4,
        ///	&quot;RandomSkillLow&quot;: 3,
        ///	&quot;RandomSkillHigh&quot;: 8,
        ///	&quot;GoodSkillRating&quot;: 8,
        ///	&quot;BadSkillRating&quot;: 3,
        ///	&quot;OpinionStrongLike&quot;: 4,
        ///	&quot;OpinionLike&quot;: 1,
        ///	&quot;OpinionDislike&quot;: -1,
        ///	&quot;OpinionStrongDislike&quot;: -4,
        ///	&quot;DislikeEventOpinionRequired&quot;: -3,
        ///	&quot;LikeEventOpinionRequired&quot;: 3,
        ///	&quot;OpinionRatingWeighting&quot;: 1,
        ///	&quot;ManagerOpinionRatingWeighting&quot;: 1,
        ///	&quot;MoodRatingWeighting&quot;: 0.5,
        ///	&quot;DefaultOpinionMin&quot;: -2,
        ///	&quot;DefaultOpinionMax&quot;: 2,
        ///	&quot;DefaultMoodMin&quot;: 0,
        ///	&quot;DefaultMoodMax&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;PromotionTriggers&quot;: [
        ///		{
        ///			&quot;StartType&quot;: &quot;Start&quot;,
        ///			&quot;NewType&quot;: &quot;Dinghy&quot;
        ///		},
        ///		{
        ///			&quot;StartType&quot;: &quot;Dinghy&quot;,
        ///			&quot;NewType&quot;: &quot;AltDinghy&quot;,
        ///			&quot;ScoreMetSinceLast&quot;: 1
        ///		},
        ///		{
        ///			&quot;StartType&quot;: &quot;AltDinghy&quot;,
        ///			&quot;NewType&quot;: &quot;BiggerDinghy&quot;,
        ///			&quot;ScoreMetSinceLast&quot;: 1
        ///		},
        ///		{
        ///			&quot;StartType&quot;: &quot;BiggerDinghy&quot;,
        ///			&quot;NewType&quot;: &quot;BiggestDinghy&quot;,
        ///			&quot;ScoreMetSinceLast&quot;: 2
        ///		},
        ///		{
        ///			&quot;StartType&quot;: &quot;BiggestDinghy&quot;,
        ///			&quot;NewType&quot;: &quot;Finish&quot;,
        ///			&quot;ScoreMetSinceLast&quot;: 2
        ///
        ///		}
        ///	],
        ///	&quot;EventTriggers&quot;: [
        ///		{        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string game_config {
            get {
                return ResourceManager.GetString("game_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;MaleForename&quot;: {
        ///		&quot;English&quot;: [
        ///			&quot;Oliver&quot;,
        ///			&quot;Jack&quot;,
        ///			&quot;Harry&quot;,
        ///			&quot;Jacob&quot;,
        ///			&quot;Charlie&quot;,
        ///			&quot;Thomas&quot;,
        ///			&quot;George&quot;,
        ///			&quot;Oscar&quot;,
        ///			&quot;James&quot;,
        ///			&quot;William&quot;,
        ///			&quot;Noah&quot;,
        ///			&quot;Alfie&quot;,
        ///			&quot;Joshua&quot;,
        ///			&quot;Muhammad&quot;,
        ///			&quot;Henry&quot;,
        ///			&quot;Leo&quot;,
        ///			&quot;Archie&quot;,
        ///			&quot;Ethan&quot;,
        ///			&quot;Joseph&quot;,
        ///			&quot;Freddie&quot;,
        ///			&quot;Samuel&quot;,
        ///			&quot;Alexander&quot;,
        ///			&quot;Logan&quot;,
        ///			&quot;Daniel&quot;,
        ///			&quot;Isaac&quot;,
        ///			&quot;Max&quot;,
        ///			&quot;Mohammed&quot;,
        ///			&quot;Benjamin&quot;,
        ///			&quot;Mason&quot;,
        ///			&quot;Lucas&quot;,
        ///			&quot;Edward&quot;,
        ///			&quot;Harrison&quot;,
        ///			&quot;Jake&quot;,
        ///			&quot;Dylan&quot;,
        ///			&quot;Ril [rest of string was truncated]&quot;;.
        /// </summary>
        public static string name_config {
            get {
                return ResourceManager.GetString("name_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;root&quot;:
        ///		{
        ///			&quot;classId&quot;: 0,
        ///			&quot;Description&quot;: null,
        ///			&quot;AppraisalRules&quot;:
        ///				{
        ///					&quot;AppraisalWeight&quot;: 1,
        ///					&quot;Rules&quot;: [
        ///						{
        ///							&quot;EventName&quot;: &quot;Event(Action-Start, Player, ManagerOpinionCheck([manager]), Self)&quot;,
        ///							&quot;Conditions&quot;:
        ///								{
        ///									&quot;Set&quot;: [&quot;Opinion([manager]) &lt; -2&quot;]
        ///								},
        ///							&quot;Desirability&quot;: -2,
        ///							&quot;Praiseworthiness&quot;: -2
        ///						}, 
        ///						{
        ///							&quot;EventName&quot;: &quot;Event(Action-Start, Player, ManagerOpinionCheck([manager]), Self)&quot;,
        ///							&quot;Conditions&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string template_ea {
            get {
                return ResourceManager.GetString("template_ea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;root&quot;:
        ///		{
        ///			&quot;classId&quot;: 0,
        ///			&quot;DefaultActionPriority&quot;: 2,
        ///			&quot;ActionTendencies&quot;: [
        ///				{
        ///					&quot;Action&quot;: &quot;RatingFeedback(Good)&quot;,
        ///					&quot;Target&quot;: &quot;-&quot;,
        ///					&quot;Type&quot;: &quot;-&quot;,
        ///					&quot;Conditions&quot;:
        ///						{
        ///							&quot;Set&quot;: [&quot;LastEventId(Action-Start, *, PositionRating([x]), SELF) = [id]&quot;, &quot;[x] &gt; 6&quot;]
        ///						},
        ///					&quot;Priority&quot;: 0
        ///				}, 
        ///				{
        ///					&quot;Action&quot;: &quot;RatingFeedback(Bad)&quot;,
        ///					&quot;Target&quot;: &quot;-&quot;,
        ///					&quot;Type&quot;: &quot;-&quot;,
        ///					&quot;Conditions&quot;:
        ///						{
        ///							&quot;Set&quot;: [&quot;LastEventId(Action-Start, *, PositionRa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string template_edm {
            get {
                return ResourceManager.GetString("template_edm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;root&quot;:
        ///		{
        ///			&quot;classId&quot;: 0,
        ///			&quot;ScenarioName&quot;: &quot;Template&quot;,
        ///			&quot;Description&quot;: null,
        ///			&quot;Dialogues&quot;: [
        ///				{
        ///					&quot;CurrentState&quot;: &quot;LearningPill&quot;,
        ///					&quot;NextState&quot;: &quot;IPCCollaboratingCollaboratingCollaboratingCompromising&quot;,
        ///					&quot;Meaning&quot;: &quot;IPCCollaboratingCollaboratingCollaboratingCompromising&quot;,
        ///					&quot;Style&quot;: &quot;IPCCollaboratingCollaboratingCollaboratingCompromising&quot;,
        ///					&quot;Utterance&quot;: &quot;IPCCollaboratingCollaboratingCollaboratingCompromisingLP&quot;,
        ///					&quot;UtteranceId&quot;: &quot;TTS-ADEE1F6FEBB48CDF7B72268F0F [rest of string was truncated]&quot;;.
        /// </summary>
        public static string template_iat {
            get {
                return ResourceManager.GetString("template_iat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;root&quot;:
        ///		{
        ///			&quot;classId&quot;: 0,
        ///			&quot;KnowledgeBase&quot;:
        ///				{
        ///					&quot;Perspective&quot;: &quot;Nameless&quot;,
        ///					&quot;Knowledge&quot;:
        ///						{
        ///
        ///						}
        ///				},
        ///			&quot;BodyName&quot;: &quot;Nameless&quot;,
        ///			&quot;VoiceName&quot;: null,
        ///			&quot;EmotionalAppraisalAssetSource&quot;: &quot;Template.ea&quot;,
        ///			&quot;EmotionalDecisionMakingSource&quot;: &quot;Template.edm&quot;,
        ///			&quot;SocialImportanceAssetSource&quot;: &quot;Template.si&quot;,
        ///			&quot;CommeillFautAssetSource&quot;: null,
        ///			&quot;EmotionalState&quot;:
        ///				{
        ///					&quot;Mood&quot;: 0,
        ///					&quot;initialTick&quot;: 0,
        ///					&quot;EmotionalPool&quot;: [],
        ///					&quot;AppraisalConfiguration [rest of string was truncated]&quot;;.
        /// </summary>
        public static string template_rpc {
            get {
                return ResourceManager.GetString("template_rpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;root&quot;:
        ///		{
        ///			&quot;classId&quot;: 0,
        ///			&quot;AttributionRules&quot;: [],
        ///			&quot;Claims&quot;: []
        ///		},
        ///	&quot;types&quot;: [
        ///		{
        ///			&quot;TypeId&quot;: 0,
        ///			&quot;ClassName&quot;: &quot;SocialImportance.SocialImportanceAsset, SocialImportanceAsset, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null&quot;
        ///		}]
        ///}.
        /// </summary>
        public static string template_si {
            get {
                return ResourceManager.GetString("template_si", resourceCulture);
            }
        }
    }
}
